# config.yml
# config for DecapCMS

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  squash_merges: true # when using editorial workflow
media_folder: "assets/uploads"

# https://decapcms.org/docs/editorial-workflows/
# This line should *not* be indented
publish_mode: editorial_workflow

collections:
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    description: "News and other public posts"
    folder: "_posts/" # The path to the folder where the documents are stored
    extension: "md"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "single" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Categories"
        name: "categories"
        hint: "Legal values include blog, news (comma separated)"
        widget: "list"
        default: ["blog", "news"]
  - name: "team"
    identifier_field: "display_name"
    label: "Team Member" # will appear as "New Team Member" in the UI"
    folder: "_team/"
    create: true
    extension: "md"
    slug: "{{slug}}" # file name will be 'name'
    preview_path: "team/{{slug}}"
    fields:
      - name: "display_name"
        label: "Display Name"
        required: true
        hint: "Your name as you wish it to appear on the team page"
        widget: "string"
        pattern: [".{5,}", "Some text is required"]
      - name: "excerpt"
        label: "One sentence bio"
        required: true
        hint: "A short description of your role or position"
        pattern: [".{20,80}", "Between 20 and 80 characters"]
      - name: body
        label: "Brief biography"
        widget: markdown
      - name: email
        label: "Preferred contact email"
        widget: string
        pattern: [".{1,}@.{1,}\\..{2,}", "Invalid email format"]
  - name: "Pages"
    label: "Pages"
    files:
      - label: "Start"
        name: "Start"
        file: "_pages/concierge.md"
        fields:
          - name: body
            widget: markdown
            label: "Text content"
      - label: "Collaborate"
        name: "Collaborate"
        file: "_pages/collaborate.md"
        fields:
          - name: body
            widget: markdown
            label: "Text content"
      - label: "Explore our data"
        name: "explore"
        file: "_pages/explore.md"
        fields:
          - name: body
            widget: markdown
            label: "Text content"
      - label: "DAP-Education"
        name: "Data Access Process for Education"
        file: "_pages/dap-education.md"
        fields:
          - name: body
            widget: markdown
            label: "Text content"
      - label: "DAP-Research"
        name: "Data Access Process for Research"
        file: "_pages/dap-research.md"
        fields:
          - name: body
            widget: markdown
            label: "Text content"
      - label: "About"
        name: "about"
        file: "_pages/about.md"
        fields:
          - name: body
            widget: markdown
            label: "Text content"
      - label: "Wiki"
        name: "wiki"
        file: "_pages/wiki.md"
        fields:
          - name: body
            widget: markdown
            label: "Text content"
